on:
  schedule:
    - cron:  '15 12 * * *' # Every day at 12:15 (noon). Ref https://crontab.guru/examples.html
name: Scrape Telegram BOT API
jobs:
  build:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: >
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Scrape website
      run: python scrape_tg_botapi.py botapi.json

    - name: Commit and push changes.
      run: |
          git checkout main

          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git commit -am "update BOT API docs."
          git push
